group = dev.yive.pluto
version = 1.21.11-R0.1-SNAPSHOT

apiVersion=1.21.11
mcVersion = 1.21.11
paperRef = 3837e9a79eccaa35fe0e27c469022c2a57b91dc9

org.gradle.jvmargs=-Xmx4G

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
