group = dev.yive.pluto
version = 1.21.11-rc3-R0.1-SNAPSHOT

apiVersion=1.21.11
mcVersion = 1.21.11-rc3
paperRef = f6e937b97856bf72e7932eccf930a405859288e8

org.gradle.jvmargs=-Xmx4G

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
