group = dev.yive.pluto
version = 1.21.11-rc1-R0.1-SNAPSHOT

apiVersion=1.21.11
mcVersion = 1.21.11-rc1
paperRef = 1cb31fd3b7b095cb1feedcf3488faa1047d82bbd

org.gradle.jvmargs=-Xmx4G

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
